services:
  local_mongo:
    image: mongo:6.0
    container_name: local_mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ../api:/usr/src/app
    networks:
      - default 

  frontend:
    build:
      context: ../ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    # volumes:
    #   - ./ui:/app
    networks:
      - default  
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - backend
      - frontend

volumes:
  mongo-db:      